/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing;

import java.awt.*;
import static javafx.application.Platform.exit;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;

/**
 *
 * @author Admin
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        setColor(btnHitung); 
        ind_1.setOpaque(true);
//        resetColor(new JPanel[]{btn_2,btn_3,btn_4}, new JPanel[]{ind_2,ind_3, ind_4});
//        jProgressBar1.setValue(50);
        btnPolaSederhana.setLabel("Pola Sederhana");
        btnPolaMajemuk.setLabel("Pola Majemuk");
        
        lblPola.setVisible(false);
        lblBenefit.setVisible(false);
        lblDetail.setVisible(false);
        jTable1.setVisible(false);
        
        btnPolaSederhana.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        btnPolaMajemuk.setFont(new Font("Segoe UI", Font.PLAIN, 14));
        lblDetail1.setForeground(new java.awt.Color(255, 255, 255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        side_pane = new javax.swing.JPanel();
        btnHitung = new javax.swing.JPanel();
        ind_1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btnExit = new javax.swing.JPanel();
        ind_3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblDetail = new javax.swing.JLabel();
        lblBenefit = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        lblPola = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txtTahunKe = new javax.swing.JTextField();
        txtBenefitAwal = new javax.swing.JTextField();
        txtKenaikan = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        btnPolaMajemuk = new java.awt.Button();
        btnPolaSederhana = new java.awt.Button();
        jLabel27 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        txtBenefitAwal2 = new javax.swing.JTextField();
        txtBenefitAwal3 = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        lblDetail1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocationByPlatform(true);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        side_pane.setBackground(new java.awt.Color(17, 45, 50));
        side_pane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnHitung.setBackground(new java.awt.Color(17, 45, 50));
        btnHitung.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnHitungMousePressed(evt);
            }
        });

        ind_1.setOpaque(false);
        ind_1.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_1Layout = new javax.swing.GroupLayout(ind_1);
        ind_1.setLayout(ind_1Layout);
        ind_1Layout.setHorizontalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_1Layout.setVerticalGroup(
            ind_1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Hitung Benefit");

        javax.swing.GroupLayout btnHitungLayout = new javax.swing.GroupLayout(btnHitung);
        btnHitung.setLayout(btnHitungLayout);
        btnHitungLayout.setHorizontalGroup(
            btnHitungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHitungLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel8)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        btnHitungLayout.setVerticalGroup(
            btnHitungLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnHitungLayout.createSequentialGroup()
                .addComponent(ind_1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, btnHitungLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        side_pane.add(btnHitung, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 170, -1));

        btnExit.setBackground(new java.awt.Color(17, 45, 50));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnExitMousePressed(evt);
            }
        });

        ind_3.setOpaque(false);
        ind_3.setPreferredSize(new java.awt.Dimension(3, 43));

        javax.swing.GroupLayout ind_3Layout = new javax.swing.GroupLayout(ind_3);
        ind_3.setLayout(ind_3Layout);
        ind_3Layout.setHorizontalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 3, Short.MAX_VALUE)
        );
        ind_3Layout.setVerticalGroup(
            ind_3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Keluar");

        javax.swing.GroupLayout btnExitLayout = new javax.swing.GroupLayout(btnExit);
        btnExit.setLayout(btnExitLayout);
        btnExitLayout.setHorizontalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );
        btnExitLayout.setVerticalGroup(
            btnExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnExitLayout.createSequentialGroup()
                .addComponent(ind_3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(btnExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        side_pane.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 170, -1));

        getContentPane().add(side_pane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 170, 590));

        jPanel2.setBackground(new java.awt.Color(37, 78, 88));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Pertumbuhan Benefit Asuransi Jiwa Berjangka");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel19)
                .addContainerGap(624, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel19)
                .addContainerGap())
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 990, 50));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"12/1/2018", "Expresso POS", "Kenya", null},
                {"12/1/2018", "ROM Gen", "US", null},
                {"12/1/2018", "Text Ed", "UK", null},
                {"12/1/2018", "Mola Con", "China", null}
            },
            new String [] {
                "Date", "Item", "Location", "Completed"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(22);
        jTable1.setVisible(false);
        jScrollPane1.setViewportView(jTable1);

        lblDetail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDetail.setForeground(new java.awt.Color(102, 102, 102));
        lblDetail.setText("Detail");

        lblBenefit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblBenefit.setForeground(new java.awt.Color(102, 102, 102));
        lblBenefit.setText("Benefit yang diperoleh nasabah : ");

        jLabel26.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        lblPola.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        lblPola.setForeground(new java.awt.Color(102, 102, 102));
        lblPola.setText("Pertumbuhan Benefit Pola");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(240, 240, 240)
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBenefit)
                    .addComponent(lblDetail)
                    .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addComponent(lblPola)
                            .addGap(100, 100, 100))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(20, 20, 20)))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblPola)
                .addGap(86, 86, 86)
                .addComponent(lblBenefit)
                .addGap(18, 18, 18)
                .addComponent(jLabel26)
                .addGap(23, 23, 23)
                .addComponent(lblDetail)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 50, 580, 540));

        jPanel4.setBackground(new java.awt.Color(136, 189, 188));
        jPanel4.setForeground(new java.awt.Color(189, 158, 191));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTahunKe.setBorder(null);
        txtTahunKe.setOpaque(false);
        txtTahunKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTahunKeActionPerformed(evt);
            }
        });
        jPanel4.add(txtTahunKe, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 280, 30));

        txtBenefitAwal.setBackground(new java.awt.Color(255, 203, 154));
        txtBenefitAwal.setBorder(null);
        txtBenefitAwal.setOpaque(false);
        txtBenefitAwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBenefitAwalActionPerformed(evt);
            }
        });
        jPanel4.add(txtBenefitAwal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 280, 30));

        txtKenaikan.setBorder(null);
        txtKenaikan.setOpaque(false);
        txtKenaikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKenaikanActionPerformed(evt);
            }
        });
        jPanel4.add(txtKenaikan, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 280, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Meninggal tahun ke-");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Benefit Awal");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Kenaikan");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        btnPolaMajemuk.setBackground(new java.awt.Color(37, 78, 88));
        btnPolaMajemuk.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPolaMajemuk.setForeground(new java.awt.Color(255, 255, 255));
        btnPolaMajemuk.setLabel("Book");
        btnPolaMajemuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolaMajemukActionPerformed(evt);
            }
        });
        jPanel4.add(btnPolaMajemuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 410, 150, 40));

        btnPolaSederhana.setBackground(new java.awt.Color(37, 78, 88));
        btnPolaSederhana.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnPolaSederhana.setForeground(new java.awt.Color(255, 255, 255));
        btnPolaSederhana.setLabel("Book");
        btnPolaSederhana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPolaSederhanaActionPerformed(evt);
            }
        });
        //btnPolaSederhana.setBorder(new RoundedBorder(10)); //10 is the radius
        jPanel4.add(btnPolaSederhana, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 150, 40));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("Form");
        jPanel4.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, -1));
        jPanel4.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel4.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel4.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
        jPanel4.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, -1, 140));
        jPanel4.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 280, -1));

        txtBenefitAwal2.setBackground(new java.awt.Color(255, 203, 154));
        txtBenefitAwal2.setBorder(null);
        txtBenefitAwal2.setOpaque(false);
        txtBenefitAwal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBenefitAwal2ActionPerformed(evt);
            }
        });
        jPanel4.add(txtBenefitAwal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 280, 30));

        txtBenefitAwal3.setBackground(new java.awt.Color(255, 203, 154));
        txtBenefitAwal3.setBorder(null);
        txtBenefitAwal3.setOpaque(false);
        txtBenefitAwal3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBenefitAwal3ActionPerformed(evt);
            }
        });
        jPanel4.add(txtBenefitAwal3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 280, 30));
        jPanel4.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 280, -1));
        jPanel4.add(jSeparator7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 280, -1));

        lblDetail1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblDetail1.setForeground(new java.awt.Color(102, 102, 102));
        lblDetail1.setText("%");
        jPanel4.add(lblDetail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, -1, -1));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 50, 360, 540));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHitungMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHitungMousePressed
        // TODO add your handling code here:
        setColor(btnHitung); 
        ind_1.setOpaque(true);
        resetColor(new JPanel[]{btnExit}, new JPanel[]{ind_1});
    }//GEN-LAST:event_btnHitungMousePressed

    private void btnExitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMousePressed
        // TODO add your handling code here:
         setColor(btnExit); 
        ind_3.setOpaque(true);
        resetColor(new JPanel[]{btnHitung}, new JPanel[]{ind_1});
        this.setVisible(false);
    }//GEN-LAST:event_btnExitMousePressed

    int xx,xy;
    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        //drag this pane
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
        
        //source to drag
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x-xx,y-xy);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void clearElement(){
        lblPola.setVisible(false);
        lblBenefit.setVisible(false);
        lblDetail.setVisible(false);
        jTable1.setVisible(false);
    };
    
    private void showElement(){
        lblPola.setVisible(true);
        lblBenefit.setVisible(true);
        lblDetail.setVisible(true);
        jTable1.setVisible(true);
    };
    private void btnPolaSederhanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolaSederhanaActionPerformed
        showElement();
        lblPola.setText("Pertumbuhan Benefit Pola Sederhana");
        
        int tahunKe = Integer.valueOf(txtTahunKe.getText());
        double benefitAwal = Double.valueOf(txtBenefitAwal.getText());
        double kenaikan = Double.valueOf(txtKenaikan.getText());
        
        
        
        /*@author Dzakira F [191524040]*/
        
        //menghitung kenaikan (%) dari benefit awal
        kenaikan = (kenaikan/100)*benefitAwal;
        
        //menghitung benefit akhir menggunakan deret aritmatika
        double benefitAkhir = benefitAwal + ((tahunKe-1)*kenaikan);
        lblBenefit.setText("Benefit yang diperoleh nasabah : " + benefitAkhir);
        
        //Mengenerate data tabel
        Object [][] dataTable= new Object [tahunKe+1][4];
        for (int i = 0; i <= 3 ; i++ ){
            dataTable[0][i] = 0;
            dataTable[1][i] = benefitAwal;
        };
        
        dataTable[1][2] = 0;
        dataTable[1][0] = 1;
        
        //benefit akhir tahun ke-n diperoleh dengan deret aritmatika
        for (int i = 2; i <= tahunKe ; i++ ){
            dataTable[i][0] = i;
            dataTable[i][1] = benefitAwal;
            dataTable[i][2] = kenaikan;
            dataTable[i][3] = benefitAwal + ((Double.valueOf(i)-1)*kenaikan);
        };
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
        dataTable,
        new String [] {
            "Tahun ke-", "Benefit Awal", "Kenaikan", "Benefit Akhir"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.Double.class, 
            java.lang.Double.class, java.lang.Double.class
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }
    });
        
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i <= 3 ; i++ ){
            jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
        };
        
    }//GEN-LAST:event_btnPolaSederhanaActionPerformed

    private void btnPolaMajemukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPolaMajemukActionPerformed
        showElement();
        lblPola.setText("Pertumbuhan Benefit Pola Majemuk");
        
        int  tahunKe = Integer.valueOf(txtTahunKe.getText());
        double benefitAwal = Double.valueOf(txtBenefitAwal.getText());
        double kenaikan = Double.valueOf(txtKenaikan.getText());
        
        
        
        
        /*@author Dzakira F [191524040]*/
        
        //menghitung kenaikan (%) dari benefit awal
        kenaikan = kenaikan/100*benefitAwal;
        
        //menghitung benefit akhir menggunakan deret geometri
        double benefitAkhir = Math.pow((benefitAwal+kenaikan),(tahunKe-1));
        lblBenefit.setText("Benefit yang diperoleh nasabah : " + benefitAkhir);
        
        //Mengenerate data tabel 
        Object [][] dataTable= new Object [tahunKe+1][4];
        for (int i = 0; i <= 3 ; i++ ){
            dataTable[0][i] = 0;
            dataTable[1][i] = benefitAwal;
        };
        
        dataTable[1][2] = 0;
        dataTable[1][0] = 1;
        
        //benefit akhir tahun ke-n diperoleh dengan deret geometri
        for (int i = 2; i <= tahunKe ; i++ ){
            dataTable[i][0] = i;
            dataTable[i][1] = dataTable[i-1][3] ;
            dataTable[i][2] = kenaikan;
            dataTable[i][3] = Math.pow((benefitAwal+kenaikan),(Double.valueOf(i)-1));
        };
        
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
        dataTable,
        new String [] {
            "Tahun ke-", "Benefit Awal", "Kenaikan", "Benefit Akhir"
        }
    ) {
        Class[] types = new Class [] {
            java.lang.Integer.class, java.lang.Double.class, 
            java.lang.Double.class, java.lang.Double.class
        };

        public Class getColumnClass(int columnIndex) {
            return types [columnIndex];
        }
    });
        
        
        
        
        
     DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        for (int i = 0; i <= 3 ; i++ ){
            jTable1.getColumnModel().getColumn(i).setCellRenderer(centerRenderer);
    };
    }//GEN-LAST:event_btnPolaMajemukActionPerformed

    private void txtBenefitAwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBenefitAwalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBenefitAwalActionPerformed

    private void txtBenefitAwal2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBenefitAwal2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBenefitAwal2ActionPerformed

    private void txtBenefitAwal3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBenefitAwal3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBenefitAwal3ActionPerformed

    private void txtTahunKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTahunKeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTahunKeActionPerformed

    private void txtKenaikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKenaikanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKenaikanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
   
    
    private void setColor(JPanel pane)
    {
        pane.setBackground(new Color(41,57,80));
    }
    
    private void resetColor(JPanel [] pane, JPanel [] indicators)
    {
        for(int i=0;i<pane.length;i++){
           pane[i].setBackground(new Color(23,35,51));
           
        } for(int i=0;i<indicators.length;i++){
           indicators[i].setOpaque(false);           
        }
        
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btnExit;
    private javax.swing.JPanel btnHitung;
    private java.awt.Button btnPolaMajemuk;
    private java.awt.Button btnPolaSederhana;
    private javax.swing.JPanel ind_1;
    private javax.swing.JPanel ind_3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBenefit;
    private javax.swing.JLabel lblDetail;
    private javax.swing.JLabel lblDetail1;
    private javax.swing.JLabel lblPola;
    private javax.swing.JPanel side_pane;
    private javax.swing.JTextField txtBenefitAwal;
    private javax.swing.JTextField txtBenefitAwal2;
    private javax.swing.JTextField txtBenefitAwal3;
    private javax.swing.JTextField txtKenaikan;
    private javax.swing.JTextField txtTahunKe;
    // End of variables declaration//GEN-END:variables
}
